// Jungle Scout <-> Claude MCP bridge
//
// Exposes a remote MCP server (Streamable HTTP transport, no auth required
// on the Claude side) that forwards tool calls to the Jungle Scout public
// API using a server-side API key. The key never leaves this server and is
// never sent back to the MCP client.
//
// Required env vars:
//   JS_API_KEY_NAME  - the "Name" column shown on the Jungle Scout Developer page
//   JS_API_KEY       - the full API key value (only shown once at generation time)
// Optional:
//   JS_DEFAULT_MARKETPLACE - default marketplace code (default: "fr")
//   PORT - provided automatically by Render

const express = require("express");
const { McpServer } = require("@modelcontextprotocol/sdk/server/mcp.js");
const { StreamableHTTPServerTransport } = require("@modelcontextprotocol/sdk/server/streamableHttp.js");
const { z } = require("zod");

const JS_API_BASE = "https://developer.junglescout.com";
const KEY_NAME = process.env.JS_API_KEY_NAME || "";
const API_KEY = process.env.JS_API_KEY || "";
const DEFAULT_MARKETPLACE = process.env.JS_DEFAULT_MARKETPLACE || "fr";

if (!KEY_NAME || !API_KEY) {
  console.error("Missing JS_API_KEY_NAME or JS_API_KEY env vars - the bridge will start but every call will fail.");
  }

  async function callJungleScout({ path, method = "POST", marketplace, body }) {
    const url = new URL(JS_API_BASE + path);
      url.searchParams.set("marketplace", marketplace || DEFAULT_MARKETPLACE);

        const res = await fetch(url.toString(), {
            method,
                headers: {
                      Authorization: KEY_NAME + ":" + API_KEY,
                            "X-API-Type": "junglescout",
                                  Accept: "application/vnd.junglescout.v1+json",
                                        "Content-Type": "application/vnd.api+json",
                                            },
                                                body: body ? JSON.stringify(body) : undefined,
                                                  });

                                                    const text = await res.text();
                                                      let parsed;
                                                        try {
                                                            parsed = JSON.parse(text);
                                                              } catch (e) {
                                                                  parsed = text;
                                                                    }

                                                                      if (!res.ok) {
                                                                          return {
                                                                                isError: true,
                                                                                      status: res.status,
                                                                                            body: parsed,
                                                                                                };
                                                                                                  }
                                                                                                    return { status: res.status, body: parsed };
                                                                                                    }
                                                                                                    
                                                                                                    function buildServer() {
                                                                                                      const server = new McpServer({
                                                                                                          name: "jungle-scout-bridge",
                                                                                                              version: "1.0.0",
                                                                                                                });
                                                                                                                
                                                                                                                  server.registerTool(
                                                                                                                      "jungle_scout_product_database_query",
                                                                                                                          {
                                                                                                                                title: "Jungle Scout - Product Database Query",
                                                                                                                                      description:
                                                                                                                                              "Search the Jungle Scout product database (equivalent to the Base de donnees produits screen). " +
                                                                                                                                                      "Use this to find products by keyword/category and get sales, revenue, review and BSR estimates.",
                                                                                                                                                            inputSchema: {
                                                                                                                                                                    marketplace: z
                                                                                                                                                                              .enum(["us", "uk", "de", "in", "ca", "fr", "it", "es", "mx", "jp"])
                                                                                                                                                                                        .default(DEFAULT_MARKETPLACE)
                                                                                                                                                                                                  .describe("Amazon marketplace to search"),
                                                                                                                                                                                                          include_keywords: z
                                                                                                                                                                                                                    .array(z.string())
                                                                                                                                                                                                                              .optional()
                                                                                                                                                                                                                                        .describe("Keywords the product listing should include"),
                                                                                                                                                                                                                                                exclude_keywords: z.array(z.string()).optional(),
                                                                                                                                                                                                                                                        categories: z.array(z.string()).optional(),
                                                                                                                                                                                                                                                                min_price: z.number().optional(),
                                                                                                                                                                                                                                                                        max_price: z.number().optional(),
                                                                                                                                                                                                                                                                                min_net: z.number().optional().describe("Minimum estimated net revenue"),
                                                                                                                                                                                                                                                                                        max_net: z.number().optional(),
                                                                                                                                                                                                                                                                                                min_reviews: z.number().optional(),
                                                                                                                                                                                                                                                                                                        max_reviews: z.number().optional(),
                                                                                                                                                                                                                                                                                                                min_rating: z.number().optional(),
                                                                                                                                                                                                                                                                                                                        max_rating: z.number().optional(),
                                                                                                                                                                                                                                                                                                                                exclude_top_brands: z.boolean().optional(),
                                                                                                                                                                                                                                                                                                                                        exclude_unavailable_products: z.boolean().optional(),
                                                                                                                                                                                                                                                                                                                                                page: z.number().optional(),
                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                              async (args) => {
                                                                                                                                                                                                                                                                                                                                                                    const { marketplace, page, ...filters } = args;
                                                                                                                                                                                                                                                                                                                                                                          const result = await callJungleScout({
                                                                                                                                                                                                                                                                                                                                                                                  path: "/api/product_database_query",
                                                                                                                                                                                                                                                                                                                                                                                          marketplace: marketplace,
                                                                                                                                                                                                                                                                                                                                                                                                  body: {
                                                                                                                                                                                                                                                                                                                                                                                                            data: {
                                                                                                                                                                                                                                                                                                                                                                                                                        type: "product_database_query",
                                                                                                                                                                                                                                                                                                                                                                                                                                    attributes: filters,
                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  isError: !!result.isError,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                server.registerTool(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "jungle_scout_api_request",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              title: "Jungle Scout - Raw API request",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Low-level escape hatch: call any Jungle Scout public API endpoint directly " +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "(see https://developer.junglescout.com/api and the Postman collection at https://postman.junglescout.com/ " +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "for the full endpoint list, e.g. keyword or sales-estimate endpoints not wrapped by a dedicated tool here). " +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Provide the path exactly as documented, starting with /api/.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          inputSchema: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  path: z.string().describe("API path, e.g. /api/product_database_query"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          method: z.enum(["GET", "POST"]).default("POST"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  marketplace: z
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .enum(["us", "uk", "de", "in", "ca", "fr", "it", "es", "mx", "jp"])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .default(DEFAULT_MARKETPLACE),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              body: z
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .record(z.any())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .optional()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .describe("JSON body to send, following the JSON API format Jungle Scout expects"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          async (args) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!args.path.startsWith("/api/")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  content: [{ type: "text", text: "path must start with /api/" }],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            isError: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const result = await callJungleScout({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        path: args.path,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                method: args.method,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marketplace: args.marketplace,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                body: args.body,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            isError: !!result.isError,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return server;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const app = express();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          app.use(express.json());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          app.get("/", (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.status(200).send("Jungle Scout MCP bridge is running.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app.post("/mcp", async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const server = buildServer();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const transport = new StreamableHTTPServerTransport({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sessionIdGenerator: undefined,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.on("close", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          transport.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                server.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await server.connect(transport);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await transport.handleRequest(req, res, req.body);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.error("MCP request error:", err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!res.headersSent) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.status(500).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    jsonrpc: "2.0",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            error: { code: -32603, message: "Internal server error" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    id: null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.get("/mcp", (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  res.status(405).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      jsonrpc: "2.0",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          error: { code: -32000, message: "Method not allowed, use POST" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              id: null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const port = process.env.PORT || 3000;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.listen(port, function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log("Jungle Scout MCP bridge listening on port " + port);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
